# Generated by Django 4.1.5 on 2023-01-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_date_alter_task_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
